gestionatr/input/messages/B1.py, gestionatr/input/messages/C1.py, gestionatr/input/messages/C2.py, gestionatr/input/messages/M1.py, gestionatr/input/messages/Q1.py, gestionatr/input/messages/R1.py, gestionatr/input/messages/W1.py, gestionatr/input/messages/message.py, gestionatr/output/messages/sw_a3.py, gestionatr/output/messages/sw_c1.py, gestionatr/output/messages/sw_c2.py, gestionatr/output/messages/sw_r1.py, gestionatr/utils.py, tests/test_input.py
Resolve warnings.
Fix found errors.
=> Fix: solve warnings and various fix

gestionatr/__init__.py
=> Bump to v0.0.2

gestionatr/input/messages/C1.py, gestionatr/input/messages/R1.py
This PR improves the way of checking if an object exists:
Uses `if obj is not None:` instead of `if obj:`
=> Improve checking if object is not None

.gitignore, README.md
This PR adds travis and coverage badges to README.md
=> Add travis and coverage badges

gestionatr/input/messages/C1.py, gestionatr/input/messages/R1.py
Method "get_rec_attr" returns "False" if some atribut doesn't exists: change checking "None" for checking "False"
=> Fix: Check boolean instead of None

gestionatr/input/messages/F1.py, gestionatr/output/messages/sw_f1.py
Fixed various mistakes on F1 importation
=> Fix: F1 imports

gestionatr/helpers/__init__.py, gestionatr/helpers/funcions.py, gestionatr/input/messages/defs.py, tests/test_helpers.py
Added required definitions/helpers
=> Add required definitions

gestionatr/defs.py
Closes https://github.com/gisce/gestionatr/issues/21
=> Cambiar 'subministro' for 'suministro'

gestionatr/__init__.py
Pre 1.0.0 version (or v1.0.0beta)
=> Bump to v0.0.6

gestionatr/input/messages/F1.py
=> Various F1 fixes

gestionatr/__init__.py
=> Bump to v0.0.7

gestionatr/input/messages/F1.py, gestionatr/output/messages/sw_f1.py
=> More fixes for F1

gestionatr/__init__.py
=> Bump to v0.0.9

gestionatr/__init__.py
=> Bump to v0.0.11

gestionatr/output/messages/base.py, tests/data/f101_factura_atr_direccion_suministro.xml, tests/test_output.py
Cut unicode text (like street) correctly
=> Fix unicode cut

gestionatr/__init__.py
=> Bump to v0.0.12

atr_test.py, gestionatr/cli.py, setup.py, tests/test_cli.py
```
Usage: atr [OPTIONS] COMMAND [ARGS]...
Options:
-v, --version  ATR library version
--help         Show this message and exit.
Commands:
test
```
command test to validate XML against XSD file
```
Usage: atr test [OPTIONS]
Options:
-f, --filename TEXT  path to XML filename  [required]
--help               Show this message and exit.
```
=> NEW atr command

gestionatr/__init__.py
=> Bump to v1.0.0

gestionatr/__init__.py
=> Bump to v1.0.1

gestionatr/input/messages/F1.py, tests/test_input.py
Changed this for getting start/end date
=> PM readings now start and end at end

MANIFEST.in, requirements-dev.txt, requirements.txt, setup.py
This PR adds the following files:
- `requirements.txt`
- `requirements-dev.txt`
=> Add requirements.txt and requirements-dev.txt files

gestionatr/input/messages/F1.py, tests/test_input.py
The reference keyword is also the 'origin' invoice number
=> Fix 'reference' is the origin invoice number too

gestionatr/__init__.py
=> Bump to v1.2.0

gestionatr/input/messages/F1.py
=> Add period 80 for dhs

gestionatr/output/messages/base.py, gestionatr/output/messages/sw_f1.py, tests/data/f101_factura_atr.xml, tests/data/f101_factura_atr_ajuste.xml, tests/data/f101_factura_atr_direccion_suministro.xml, tests/data/f101_factura_atr_empty_periods.xml, tests/data/f101_factura_atr_medidas_baja.xml, tests/data/f101_factura_empty_rent.xml, tests/data/f101_spaces.xml
F1: Force fields with 0 instead of being empty
=> F1: Force fields with 0 instead of being empty

gestionatr/defs.py
The new draft version only have 00 and 01 values
=> FIX BONO SOCIAL TABLA 116 without 02 value

gestionatr/defs.py
Add Jafre (0224) code to be mapped as ENDESA CUPS on atr files
=> NEW Jafre as ENDESA

gestionatr/output/messages/sw_f1.py
=> Añadir importe a la estructura de IVA reducido y dedondear decimales

gestionatr/input/messages/F1.py
Añadir parametro en `get_contracted_periods_by_period` para utilizar la facturada
=> Añadir parametro en `get_contracted_periods_by_period` para utilizar la facturada

gestionatr/defs.py, gestionatr/defs_gas.py, gestionatr/input/messages/A1_48.py, gestionatr/output/messages/sw_a1_48.py, tests/test_output.py
=> Mejoras proceso A1_48

gestionatr/defs.py
=> R1: corregir campos minimos subtipos 068 y 069

gestionatr/input/messages/R1.py, tests/data/r103_no_add_info.xml, tests/test_input.py
A R1-03 file without `SolicitudInformacionAdicional` doesn't parse
=> Fix r1 03 without solicitud informacion adicional

gestionatr/input/messages/F1.py, gestionatr/utils.py, requirements.txt
Se repartia mal cuando habia varios contadores.
=> Corregir get_lectures_amb_ajust_autoconsum

gestionatr/input/messages/F1.py
Mejorar el metodo de calcular ajustes balanceados al consumo para que sea mas generico
=> Mejorar el metodo de calcular ajustes balanceados al consumo

gestionatr/output/messages/sw_a1.py
FIX tag erróneo en output de A102Fixes output bug in A102
=> FIX tag erróneo en output de A102Fixes output bug in A102

gestionatr/defs.py
Missing Installed Power info in TABLE 126 (generation tecnologies)
=> FIX TABLE 126 descriptions for hydraulic

gestionatr/output/messages/sw_r1.py, tests/data/r108.xml, tests/test_output.py
=> IMP Añadir paso r108 out

gestionatr/input/messages/F1.py
Añade método para recuperar el valor del coeficiente de reparto de un F1
=> Añade método para recuperar el valor del coeficiente de reparto de un F1

gestionatr/input/messages/B70.py
Actualitzats els camps del B70 per poder gestionar els caudals dels mesuradors, necessaris per processar tarifes 2.1
=> Add new fields to B70 for caudal

gestionatr/utils.py
Add missing former switching library function `rodes`
=> NEW rodes function

gestionatr/input/messages/F1.py
La mandanga del dia by iberdrola
=> Transofrmar a TD les lectures pre TD  en un F1 amb lectures noves i antigues a la vegada

gestionatr/input/messages/F1.py
Añade método para lecturas con decimales
=> Añade método para lecturas con decimales

gestionatr/input/messages/F1.py
Fixes excesos de potencia retrieving
=> Fixes excesos de potencia herencia de periodo

gestionatr/input/messages/F1.py
Corrige comprovación de ajuste
=> Corrige comprovación de ajuste

gestionatr/input/messages/F1.py
FIX cálculo de maxímtros consumidor como float
=> FIX cálculo de maxímtros consumidor como float

gestionatr/defs.py
=> Añadida nueva tabla 87

atr_test.py, gestionatr/defs.py
Añade nuevos tipos en las tablas de definiciones y arregla mensaje error en atr_test
=> Añade nuevos tipos en las tablas de definiciones y arregla mensaje error en atr_test

gestionatr/input/messages/F1.py
=> Minor fixes

gestionatr/input/messages/F1.py
Recuperar el tipo de punto de medida del F1
=> Recuperar el tipo de punto de medida del F1

gestionatr/data/B7031.xsd, gestionatr/data/B7032.xsd, gestionatr/data/B7033.xsd, gestionatr/data/CommonTagsFACT.xsd, gestionatr/input/messages/B70.py
Adaptacion de gestionatr para leer el campo "codtbai".
=> [25801] UPG Cambios necesarios para leer el campo "codtbai"

gestionatr/input/messages/F1.py
Corrección concepto 87 que no importa porque el importe es 0
=> Corrección concepto 87 que no importa porque el importe es 0

gestionatr/input/messages/F1.py
FIX regularizadoras cuando hay lecturas pre TD en un solo periodo
=> FIX regularizadoras cuando hay lecturas pre TD en un solo periodo

gestionatr/input/messages/F1.py
Cambios menores para reposiciones y facturas con base del IVA 0
=> Cambios menores para reposiciones y facturas con base del IVA 0

.github/workflows/python-app.yml, gestionatr/defs.py
=> Añadir rechazo H4

gestionatr/input/messages/B70.py
Es verifica que primerament es tingui el valor pcs abans d'utilitzar-lo per calcular.
=> check if there is pcs before division

gestionatr/input/messages/message_gas.py
No es podia tractar els casos A2S02, ja que no hi havia la relacio creada.
=> Fix: add A2S02 Support

gestionatr/data/A1225.xsd, gestionatr/data/A1239.xsd, gestionatr/data/A1350.xsd, gestionatr/data/A138.xsd, gestionatr/data/A1550.xsd, gestionatr/data/A302.xsd, gestionatr/data/A338.xsd, gestionatr/data/A341.xsd, gestionatr/data/A342.xsd
Corrección temporal de ATR 2.6 a la espera de aprovación de Orden de la CNMC y del ministerio para GAS
=> Corrección temporal de ATR 2.6 a la espera de aprovación de Orden de la CNMC y del ministerio para GAS

gestionatr/input/messages/message.py
:lady_beetle: https://sentry.monitoring.gisce.net/organizations/gisce/issues/35338/?query=is%3Aunresolved+%21level%3Awarning+%21message%3Awarning+assigned%3Anone&referrer=issue-stream&stream_index=3
=> FEAT: Add exception type on except_F1 exception to decide which to send to Sentry

gestionatr/input/messages/B70.py
=> Evitar factores k negativos al importar B70 incorrectos

gestionatr/input/messages/F1.py
=> Revert "Facturar términos de autoconsumo aunque éstos sean 0"
