gestionatr/output/messages/base.py, tests/test_output.py
When the field with fixed size (`rep_cut()`) is empty, do not write anything.
=> Fix rep cut when empty

gestionatr/input/messages/R1.py, gestionatr/input/messages/message.py
In R1 the CUPS is not allways required. Don't raise error if we don't have cups.
=> Manage R1 without CUPS

gestionatr/output/messages/sw_c1.py, tests/data/c105.xml, tests/data/c106.xml, tests/test_input.py, tests/test_output.py
Allow measures 0.0.
The generated XML fails otherwise
=> FIX 0 measures output

gestionatr/input/messages/F1.py
Se aplicaba un strip en los comentarios de los F1's, esto es un problema muy grande en algunos casos ya que los espacios son importantes, ahora ya no se hace strip. ej. Suplementos
=> Dont strip comments f1, spaces are important in some cases.

gestionatr/input/messages/F1.py
Obtener el código de punto de medida cuando se llama la función `get_comptadors`.
=> Código de Punto de Medida en la información del contador

gestionatr/data/A101.xsd, gestionatr/data/A102.xsd, gestionatr/data/TipoMensajeA101.xsd, gestionatr/data/TipoMensajeA102.xsd, gestionatr/data/TipoMensajeRechazoCCAA.xsd, gestionatr/data/TiposComplejosCCAA.xsd, gestionatr/input/messages/A1.py, gestionatr/output/messages/sw_a1.py, tests/data/a102_accept.xml, tests/data/a102_reject.xml, tests/test_input.py, tests/test_output.py
Cambios realizados en A102 debido a nuevas especificaciones de la CNMC.
Se modifica el paso A102 de la siguiente manera:
- Se elimina el boque 'ActualizacionDatosRegistro' de la aceptación
- Se mueve la 'FechaRechazo' fuera de los Rechazos individuales al bloque superior 'Rechazos'
- Se elimina el CUPS informado en los rechazos.
Se detecta un bug en el XSD 'TipoMensajeA102.xsd' por el que se obliga a informar rechazos aunque se trate de un mensaje de aceptación.
Se añaden los XSD oportunos.
=> Cambios realizados en A102 debido a nuevas especificaciones de la CNMC

gestionatr/input/messages/F1.py
Algunos F1 no se cargan correctamente: salta el error `2002` conforme el total de la factura de proveedor creada no coincide con el del F1 cargado
El F1 cargado **no** tiene impuestos en el tag `IVA` (es una compensación) pero si que tiene en el tag `IVAReducido`. El proceso de carga de F1 asigna los impuestos a las lineas de la factura solamente si el tag de `IVA` tiene impuestos. Al no tenerlos, ignora las impuestos de `IVAReducido` y crea las líneas sin impuesto alguno provocando que el importe de la factura no cuadre con el del F1.
Se pueden encontrar en https://github.com/gisce/erp/pull/10699
=> No se contempla el tag IVAReducido

gestionatr/input/messages/F1.py, gestionatr/utils.py
- Repartir ajustos autoconsum  entre els periodes per evitar voltes de contador 
- Quan ens cobren excedents pero no ens informen lectures, ens inventem unes lectures AS a 0 per poder processar el F1
=> Millores en les lectures i ajustos per autoconsum

gestionatr/data/TiposComplejos.xsd, gestionatr/data/TiposSencillos.xsd, gestionatr/input/messages/C1.py
Se permiten poblaciones de menos de 11 caracteres aunque segun la CNMC deban tener 11 caracteres ya que la mayoria de distribuidoras no cumplen el requisito y resulta en ficheros que no se pueden processar
=> Permitir poblaciones de menos de 11 caracteres

gestionatr/input/messages/message.py
Algunas empresas envían la fecha de solicitud con milisegundos. Se eliminan dichos milisegundos para no afectar a la carga de ficheros switching
=> Evitar milisegundos en fecha de solicitud de casos ATR de electricidad

gestionatr/input/messages/F1.py
Cuando la tarifa es de periodo único, no entrar en la lógica de P0 de generación
=> Cuando la tarifa es de periodo único, no entrar en la lógica de P0 de generación

gestionatr/cli.py
Permite crear una petició P0 des de los parámetros de la linea de comandos
```shell
$ atr p0 -u https://localhost/Sync?WSDL -s $WS_USER -p $WS_PASSWORD \
--emisora $REE_EMISORA --destino $REE_DESTINO --cups $CUPS
```
=> Allow to create P0 from CLI params

gestionatr/data/TiposSencillos.xsd, gestionatr/defs.py
Se añade conceptos 84 y 85 para electrointensivos:
- '84', 'Descuento en peajes de transporte y distribución de electricidad a la industria electrointensiva'
- '85', 'Regularización descuento en peajes de transporte y distribución de electricidad a la industria electrointensiva'
=> Añade conceptos 84 y 85 para electrointensivos.

gestionatr/input/messages/B70.py
- Al crear una modificación contractual cuando se importa un B70, se tienen que escoger las fechas de inicio y fin según el tipo de concepto de esta. Vamos a escoger las fechas de los conceptos que sean de término fijo o de término variable
- Se escogian mal las fechas de inicio y de fin para crear la nueva modificación contractual
- Se ha creado un nuevo método que nos filtra, a la hora de buscar las fechas, según los conceptos del B70
=> Escoger correctamente las fechas al crear una modcon al importar un B70

gestionatr/data/Facturacion.xsd, gestionatr/data/TiposComplejos.xsd, gestionatr/data/TiposSencillos.xsd, gestionatr/input/messages/F1.py, gestionatr/output/messages/sw_f1.py, tests/data/f101_factura_atr.xml, tests/data/f101_factura_atr_autoconsum_20td.xml, tests/data/f101_factura_atr_direccion_suministro.xml, tests/data/f101_factura_atr_medidas_baja.xml, tests/test_input.py, tests/test_output.py
- Comunicar la energía consumida por código postal por cada mes natural.
=> Mejorar la gestión de F1 para poder comunicar el valor energético medio de tu Codigo Postal

gestionatr/input/messages/B70.py
Cuando se piden las lecturas del B70 ahora también se envían los campos de <temp> (Temperatura gas) y <presatm> (Presión atmosferica) para utilizarlas para corregir las lecturas de gas sucias
=> Coger campos necesarios para facturar lecturas sucias de gas

gestionatr/defs.py
Según sea el tipo de la instalación de generación(TABLA_126) tendrá una disponibilidad u otra. Este dato se utiliza para facturar el concepto de operador de mercado en representación
BOE:
https://www.boe.es/diario_boe/txt.php?id=BOE-A-2022-23737 <-- Punto Octavo
=> Añadir disponibilidad de instalación de generación para facturar operador mercado representación

gestionatr/defs.py
Se añede el motivo 15 (Alta en autoconsumo colectivo comunicada por un participante) en la tabla 109 (Motivo Cambio ATR Desde Distribuidora) porque endesa empezara a enviar D1 con este motivo de cambio
=> Añadir motivo numero 15 en tabla 109 de motivos de cambio atr desde distribuidora

gestionatr/data/TiposSencillos.xsd, gestionatr/defs.py
El motivo 15 cambia de texto:
De     "Alta en autoconsumo colectivo comunicada por un participante"
A       "Alta en autoconsumo colectivo comunicada por un representante"
=> Cambio de nombre motivo 15 D101 de alta autoconsumo

gestionatr/input/messages/F1.py
La función `get_fake_AS_p2_lectures` se llamaba cuando un se cogian las lecturas de un F1 que venia con solo una lectura para energia exportada y se creaban 2 lecturas "falsas". El problema era que esto se hacia también cuando se importaban lecturas de pool de un F1 de un contrato con tarifa 2.0TD(con motivo de ajuste "FORZADO DEBIDO A LA NO ADAPTACIÓN A LA TARIFA) que solo tenia una lectura para un periodo de energia entrante y energia saliente. Se ha cambiado la condición para que la función se llame `get_fake_AS_p2_lectures` cuando se trate de antiguas tarifas 
Para las nuevas se utiliza la función `transforma_no_td_a_td` que pasa de tarifa antigua a tarifa nueva y lo que pasaba es que si se llamaba `get_fake_AS_p2_lectures` despues las lecturas no eran compatibles con …
=> FIX Al importar lecturas de pool de F1 con unico periodo de nuevas tarifas se creaban mal los ajustes

gestionatr/input/messages/F1.py
Si la tarifa es 2.0TD y el F1 indica valor de coeficiente de reparto para los 6 periodos, se eliminan los periodos P4, P5, Y P6 ya que no corresponden a esa tarifa.
=> Mejorar el método "get_coeficient_repartiment" para que tenga en cuenta los periodos según la tarifa

gestionatr/input/messages/B70.py
Verificar que tenemos la variable consumo_m3 antes de utilizarla para dividir y que salte un posible error por division entre 0
=> Comprovar que tenemos todas las variables, para prevenir division por 0

gestionatr/input/messages/F1.py
=> Nuevo método para obtener los IVAS reducidos del F1

gestionatr/input/messages/F1.py
Si nos envian las lecturas de Activa del contador de generación, y este está configurado con 6 periodos, pero el contrato tenia una tarifa ATR de 3 periodos, fallaba al obtener las lecturas.
Por ese motivo, a partir de ahora se ignoran las lecturas del contador cuyo periodo esté fuera de los periodos de la tarifa del contrato
=> Permitir obtener lecturas del F1 si el CG tiene mas periodos que la tarifa del contrato

gestionatr/input/messages/R1.py
Corrección en la validación de un R1 -03 tipo 076 "CONSULTA SEGUIMIENTO AUTOCONSUMO" en que, solicita número de acometida incorrectamente. Es obligatorio cuándo únicamente el motivo de consulta es tipo 02.
=> Corrección validación numero expediente acometida cuando es motivo consulta 02

gestionatr/input/messages/F1.py
TEST: https://github.com/gisce/gestionatr/pull/272
En ocasiones en los F1 nos encontramos con diferentes etapas donde nos muestra el valor de la energía para cada periodo:
```
<EnergiaActiva>
<TerminoEnergiaActiva>
<FechaDesde>2022-10-19</FechaDesde>
<FechaHasta>2022-12-31</FechaHasta>
<Periodo>
<ValorEnergiaActiva>+00000000032.61</ValorEnergiaActiva>
<PrecioEnergia>00000.02778700</PrecioEnergia>
</Periodo>
...
<TerminoEnergiaActiva>
<FechaDesde>2022-12-31</FechaDesde>
<FechaHasta>2023-12-31</FechaHasta>
<Periodo>
<ValorEnergiaActiva>-00000000000.24</ValorEnergiaActiva>
<PrecioEnergia>00000.02909800</PrecioEnergia>
</Periodo>
<Periodo>
```
Pero los cargos de la energía se agrupan de la siguiente forma:
```
<TerminoCargo>
<FechaDesde>2022-12-31</FechaDesde> …
```
=> Asignar precios de cargos correctamente cuando esten agrupados

gestionatr/input/messages/F1.py
En caso de haber totalizadores, para evitar tener casos de lecturas 90, 91, 92, 93, solo se tenían en cuenta los totalizadores si tenian eran de una fecha distinta a las lecturas normales, o si eran de un periodo distinto.
En caso de que fueran de magnitudes distintas, no se tenían en cuenta, dando problema a la hora de cargar las lecturas.
Ejemplo:
`2025-05-31`:
-  AE -> 91, 92, 93
- AS -> 90
- PM -> 91,93
Se filtra tambien por magnitud, es decir, por mucho que sean de la misma fecha y del mismo periodo que otras lecturas que tengamos, si son de distinta magnitud, por ejemplo `AS`, tambíen se tienen en cuenta.
=> Corregir importación de F1s con lecturas totalizadoras código 90 y A0

gestionatr/input/messages/F1.py
Desactivar el metodo para detectar facturacion de periodos agrupada porque hace que se importen mal los ajustes en casos muy concretos
=> Desactivar detección de periodos agrupados para tarifas 3.0A (deprecated)

gestionatr/input/messages/F1.py
- `compt_xml.get_lectures_activa_sortint_sense_quadrar_ajustos` -> Nuevo método para obtener las lecturas de activa saliente sin calcular ajustes.
- `fact_xml.get_lectures_activa_sortint` -> Nuevo named param `lectures:None`, para poder indicar las lecturas sobre las cuales se tienen que cuadrar los ajustes.
- `compt_xml.get_fake_AS_lectures`-> Nuevo named param `comptador_base:None`, para poder asignar el contador de la lectura original a las lecturas ficticias.
- `compt_xml.get_fake_pX_lectura`-> Nuevo named param `comptador_base:None`, para poder asignar el contador de la lectura original a las lecturas ficticias
- `compt_xml.get_fake_AS_p2_lectures`-> Nuevo named param `comptador_base:None`, para poder asignar el contador de la lectura original a las lecturas ficticias
=> Nuevos métodos para obtener lecturas AS sin calcular ajustes
